### PR TITLE
syntax error near unexpected token `&' in /CHAP_modules/CHAP_deffxn.sh and /CHAP_modules/CHAP_ana.sh

### PR DESCRIPTION
**Pull request by pritampanda15**
When I ran 
```
run_CHAPERONg.sh
```
The following errors were shown:
```
/Users/pritam/Downloads/CHAPERONg-main/CHAP_modules/CHAP_deffxn.sh: line 2136: syntax error near unexpected token `&'
(base) ➜  Downloads run_CHAPERONg.sh
/Users/pritam/Downloads/CHAPERONg-main/CHAP_modules/CHAP_deffxn.sh: line 2356: syntax error near unexpected token `&'
(base) ➜  Downloads run_CHAPERONg.sh
/Users/pritam/Downloads/CHAPERONg-main/CHAP_modules/CHAP_deffxn.sh: line 2373: syntax error near unexpected token `&'
(base) ➜  Downloads run_CHAPERONg.sh
/Users/pritam/Downloads/CHAPERONg-main/CHAP_modules/CHAP_ana.sh: line 213: syntax error near unexpected token `&'
(base) ➜  Downloads run_CHAPERONg.sh
/Users/pritam/Downloads/CHAPERONg-main/CHAP_modules/CHAP_ana.sh: line 230: syntax error near unexpected token `&'
```

So I have removed "&" from the code and it worked again:

```
run_CHAPERONg.sh
 
############################################################################### 
#--------------------------------- CHAPERONg ---------------------------------# 
#              If you use this program in your work, please cite:             # 
#  Yekeen A.A., Durojaye O.A., Idris M.O., Muritala H.F., Arise R.O. (2023).  # 
#      CHAPERONg: A tool for automated GROMACS-based molecular dynamics       # 
#   simulations  and  trajectory  analyses,  Computational  and  Structural   # 
#                    Biotechnology Journal 21: 4849-4858.                     # 
############################################################################### 

##*********************************CHAPERONg**********************************##

 What type of simulation do you want to run?
  (1)  Conventional MD simulation -- Unbiased/Regular
  (2)  Enhanced (umbrella) sampling simulation -- Biased

 *ENTER YOUR CHOICE HERE (1 or 2): 

```

### CODE REVIEW

**Comment by pritampanda15** [comment]
By the way I am using MacOS

**Comment by pritampanda15** [comment]
Moreover, networkx 2.3 does not seem to work for cgenff_charmm2gmx_py3_nx2.py. So updated to networkx 2.5 and it works.
Error:
```
python cgenff_charmm2gmx_py3_nx2.py                       
Traceback (most recent call last):
  File "/Users/pritam/Downloads/Protein-Ligand-umbrella-sampling-input-files/cgenff_charmm2gmx_py3_nx2.py", line 54, in <module>
    import networkx as nx
  File "/Users/pritam/anaconda3/lib/python3.11/site-packages/networkx/__init__.py", line 114, in <module>
    import networkx.generators
  File "/Users/pritam/anaconda3/lib/python3.11/site-packages/networkx/generators/__init__.py", line 14, in <module>
    from networkx.generators.intersection import *
  File "/Users/pritam/anaconda3/lib/python3.11/site-packages/networkx/generators/intersection.py", line 13, in <module>
    from networkx.algorithms import bipartite
  File "/Users/pritam/anaconda3/lib/python3.11/site-packages/networkx/algorithms/__init__.py", line 16, in <module>
    from networkx.algorithms.dag import *
  File "/Users/pritam/anaconda3/lib/python3.11/site-packages/networkx/algorithms/dag.py", line 23, in <module>
    from fractions import gcd
ImportError: cannot import name 'gcd' from 'fractions' (/Users/pritam/anaconda3/lib/python3.11/fractions.py)
```
Solved by updating to networkx=2.5 installed via pip install networkx==2.5 
```
python cgenff_charmm2gmx_py3_nx2.py
Usage: RESNAME drug.mol2 drug.str charmm36.ff
```

However, in conda environment, networkx==2.3 works perfectly.

File: CHAP_modules/CHAP_ana.sh
Comment (abeebyekeen) [inline CHAP_modules/CHAP_ana.sh:1]: Thanks! Please replace `|&` with `2>&1 |` and see if it works. It's better to have the stderr also redirected to the log file. Good for debugging in case the terminal details get lost.

File: CHAP_modules/CHAP_deffxn.sh
Comment (abeebyekeen) [inline CHAP_modules/CHAP_deffxn.sh:1]: Please replace `|&` with `2>&1 |` and see if it works. Thanks!

File: conda_dependencies.yml [hunk 1]
```diff
@@ -17,7 +17,7 @@ dependencies:
 # Although numpy 1.18.5 & 1.23.4 both worked with python 3.8.10, 3.8.13, 3.8.15, 3.8.16
     - matplotlib # tested versions: 3.6.1, 3.6.2, 3.6.3
     # - pycairo
-    - networkx==2.3
+    - networkx==2.5
```
Comment (abeebyekeen) [inline conda_dependencies.yml]: Thanks! I'm guessing it probably has something to do with your python version. Networkx is a little finicky. To avoid breaking other things/potential incompatibility with other setups, I would add `- network==2.5` as a comment in the yaml file for other users and also point this issue out in the installation guide.

**Review by abeebyekeen — CHANGES_REQUESTED** [review]

**Comment by abeebyekeen** [comment]
> By the way I am using MacOS

Thanks for the info. Never tested on MacOS. The error has to do with different bash versions. Found that `|&` doesn't work with all version. Replacing `|&` with `2>&1 |` should work--`2>&1 |` has a much wider support. It's better to have the stderr also redirected to the log file. Good for debugging in case the terminal details get lost.

File: CHAP_modules/CHAP_ana.sh
Comment (pritampanda15) [reply CHAP_modules/CHAP_ana.sh:1]: Thanks. I will check it out!

File: conda_dependencies.yml (hunk 1 above)
Comment (pritampanda15) [reply conda_dependencies.yml]: Just to remember that you should not install (avoid) networkx=2.4 which is unstable and lot of bugs.

Comment (abeebyekeen) [reply conda_dependencies.yml]: Thanks. I have also added a note about ` networkx == 2.5` in the docs. Thanks for the additional info on `2.4`

File: CHAP_modules/CHAP_deffxn.sh [hunk 2]
```diff
@@ -2133,7 +2133,7 @@ ScanTRAJ_SMD()
 if [[ ! -f "SMD_trajectDetails.log" ]]; then
 	echo "${demA}"$' Checking the SMD trajectory to extract info about the number of frames and\n simulation time'"${demB}"
 	sleep 2
-	eval $gmx_exe_path check -f pull.xtc | tee SMD_trajectDetails.log
+	eval $gmx_exe_path check -f pull.xtc 2>&1 tee SMD_trajectDetails.log
```
Comment (abeebyekeen) [inline CHAP_modules/CHAP_deffxn.sh]: It should be **`2>&1 |`**. The pipe is missing. Thanks!

File: CHAP_modules/CHAP_deffxn.sh [hunk 3]
```diff
@@ -2353,7 +2353,7 @@ fi
 if [[ ! -f "trajectDetails.log" ]]; then
 	echo -e "${demA} Checking the trajectory to extract info about the number of frames and\n simulation time${demB}"
 	sleep 2
-	eval "$gmx_exe_path" check -f "${filenm}"_${wraplabel}.xtc | tee trajectDetails.log
+	eval "$gmx_exe_path" check -f "${filenm}"_${wraplabel}.xtc 2>&1 tee trajectDetails.log
```
Comment (abeebyekeen) [inline CHAP_modules/CHAP_deffxn.sh]: It should be **`2>&1 |`**. The pipe is missing. Thanks!

File: CHAP_modules/CHAP_deffxn.sh [hunk 4]
```diff
@@ -2370,7 +2370,7 @@ else
 	{
 		echo -e "${demA} Checking the trajectory to extract info about the number of frames and\n simulation time${demB}"
 		sleep 2
-		eval "$gmx_exe_path" check -f "${filenm}"_${wraplabel}.xtc | tee trajectDetails.log		
+		eval "$gmx_exe_path" check -f "${filenm}"_${wraplabel}.xtc 2>&1 tee trajectDetails.log
```
Comment (abeebyekeen) [inline CHAP_modules/CHAP_deffxn.sh]: It should be **`2>&1 |`**. The pipe is missing. Thanks!

**Review by abeebyekeen — CHANGES_REQUESTED** [review]
It should be **`2>&1 |`**. The pipe is missing. Thanks!

File: conda_dependencies.yml (hunk 1 above)
Comment (abeebyekeen) [reply conda_dependencies.yml]:
```bash
    - networkx==2.3
# if nextworkx==2.3 fails, try networkx==2.5    
    # - networkx==2.5
```
Since `2.3` works in the conda env, could you add the above in the yaml so I can merge.

File: CHAP_modules/CHAP_ana.sh [hunk 5]
```diff
@@ -210,7 +210,7 @@ fi
 if [[ ! -f "trajectDetails.log" ]]; then
 	echo -e "${demA} Checking the trajectory to extract info about the number of frames and\n simulation time${demB}"
 	sleep 2
-	eval "$gmx_exe_path" check -f "${filenm}"_${wraplabel}.xtc | tee trajectDetails.log
+	eval "$gmx_exe_path" check -f "${filenm}"_${wraplabel}.xtc |2>&1 | tee trajectDetails.log
```
Comment (abeebyekeen) [inline CHAP_modules/CHAP_ana.sh]: It should be **`2>&1 |`** and NOT **`|2>&1 |`**. Just the second pipe. Thanks!

File: CHAP_modules/CHAP_ana.sh [hunk 6]
```diff
@@ -227,7 +227,7 @@ else
 	{
 		echo -e "${demA} Checking the trajectory to extract info about the number of frames and\n simulation time${demB}"
 		sleep 2
-		eval "$gmx_exe_path" check -f "${filenm}"_${wraplabel}.xtc | tee trajectDetails.log		
+		eval "$gmx_exe_path" check -f "${filenm}"_${wraplabel}.xtc |2>&1 | tee trajectDetails.log
```
Comment (abeebyekeen) [inline CHAP_modules/CHAP_ana.sh]: It should be **`2>&1 |`** and NOT **`|2>&1 |`**. Just the second pipe. Thanks!

**Review by abeebyekeen — APPROVED** [review]

**Review by abeebyekeen — APPROVED** [review]

**Review by abeebyekeen — APPROVED** [review]
